# Generated by Django 3.1.4 on 2021-01-18 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=50)),
                ('scholarship', models.BooleanField(default=False)),
            ],
        ),
    ]
